### ISSUE TITLE
user profile controllers

### ISSUE THREAD

**Issue by tarik310** [OmarQaqish/cook-link#56]
the user controllers will eanble to update information of the user as following:
• update username, firstName, lastName, and password.
• upload picture

**Comment by OmarQaqish** [comment]
Hey @tarik310 could you please take a look at the pull request I created just now for address routes and controllers just so we make sure we're not doing the same thing? 😄 Since you have "add address information" here

**Comment by tarik310** [comment]
yeah sorry I forgot it
